- name: Setup Theos
  uses: mertsteam/theos-action@v2.4.6   # ← kendi fork'un yerine orijinali kullan
  with:
    theos-src: 'theos/theos'
    theos-branch: 'main'
    sdks-src: 'theos/sdks'
    sdks-branch: 'master'
    libgcuniversal: 'true'
    altlist: 'true'
